import type { Metadata } from 'next';
import '#@/styles/globals.css';
import 'material-symbols';
import Layout from '#@/components/layout';
import { ReactNode } from 'react';
import { josefina, playDisp, ptserif, radio, raleway } from '#@/styles/fonts';
import PushManagerComponent from '#@/components/PushManager';
import { PushNotificationProvider } from './context/pushNotificationContext';
import { CssBaseline,
  InitColorSchemeScript,
  ThemeProvider, } from '@mui/material';
// This is MUI's official SSR cache provider for Next.js App Router
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import theme from './theme';

export const metadata: Metadata = {
  title      : 'My Portfolio', // Updated this from the Next.js default!
  description: 'Generated by create next app',

};

export default function RootLayout( {
  children,
}: Readonly<{
  children: ReactNode;
}> ) {
  return (
    <html lang="es-CO" suppressHydrationWarning>
      <head>
        <meta name="apple-mobile-web-app-title" content="Portfolio" />
      </head>
      <body
        className={`${ playDisp.variable } ${ josefina.className } ${ raleway.variable } ${ radio.variable } ${ ptserif.variable } [ color-scheme: light dark ]`}
      >
        <InitColorSchemeScript attribute="data" defaultMode="system"/>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <PushNotificationProvider>
              <PushManagerComponent />
              <Layout>{children}</Layout>
            </PushNotificationProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}