import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '#@/styles/globals.css';
import Layout from '#@/components/layout';
import { ReactNode } from 'react';
import { josefina, playDisp, ptserif, radio, raleway } from '#@/styles/fonts';
import PushManagerComponent from '#@/components/PushManager';
import { PushNotificationProvider } from './context/pushNotificationContext';

const geistSans = Geist( {
  variable: '--font-geist-sans',
  subsets : [
    'latin'
  ],
} );

const geistMono = Geist_Mono( {
  variable: '--font-geist-mono',
  subsets : [
    'latin'
  ],
} );

export const metadata: Metadata = {
  title      : 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: ReactNode;
}> ) {
  return (
    <html lang="es-CO">
      <body className={ `${ playDisp.variable } ${ josefina.className } ${ raleway.variable } ${ radio.variable } ${ ptserif.variable } [ color-scheme: light dark ]` }>
        <PushNotificationProvider>
          <PushManagerComponent />
          <Layout>{ children }</Layout>
        </PushNotificationProvider>
      </body>
    </html>
  );
}
