import type { Metadata } from 'next';
import '#@/styles/globals.css';
import 'material-symbols';
import Layout from '#@/components/layout';
import { ReactNode } from 'react';
import { josefina, playDisp, ptserif, radio, raleway } from '#@/styles/fonts';
import PushManagerComponent from '#@/components/PushManager';
import { PushNotificationProvider } from './context/pushNotificationContext';
import { CssBaseline,
  InitColorSchemeScript,
  ThemeProvider, } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import theme from './theme';

export const metadata: Metadata = {
  title      : 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: ReactNode;
}> ) {
  return (
    <html
      lang="es-CO"
      suppressHydrationWarning
    >
      <body
        className={`${ playDisp.variable } ${ josefina.className } ${ raleway.variable } ${ radio.variable } ${ ptserif.variable } [ color-scheme: light dark ]`}
      >
        <InitColorSchemeScript
          attribute="class"
          defaultMode="system"
        />
        <AppRouterCacheProvider>
          <ThemeProvider
            theme={theme}
            defaultMode="system"
          >
            <CssBaseline />
            <PushNotificationProvider>
              <PushManagerComponent />
              <Layout>{children}</Layout>
            </PushNotificationProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
